@echo off
echo Checking dependencies...
IF NOT EXIST "node_modules\" (
    echo node_modules not found. Installing dependencies...
    npm install
)
echo Starting Tauri development server...
npm run tauri dev
